### ISSUE TITLE
need to add this to fuse third party list

### ISSUE THREAD

**Issue by devmondo** [otothea/fuse-box-graphql-plugin#1]
Hi,

great work there! we would love to add this to third-party plugins list on fuse site, but could you please do the following to make it look better :)

- move https://github.com/otothea/fuse-box-graphql-plugin/blob/master/index.js#L1 to transform function
- add some better details in readme file.

we appreciate your work with fuse-box :)

**Comment by otothea** [comment]
sorry it took me 4 months to respond to this, but I made the suggested adjustments
